package:
  name: ros-foxy-tf2-ros
  version: 0.13.9
source:
  git_url: https://github.com/ros2-gbp/geometry2-release.git
  git_rev: release/foxy/tf2_ros/0.13.9-1
  folder: ros-foxy-tf2-ros/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
  host:
    - python
    - ros-foxy-ament-cmake
    - ros-foxy-ament-cmake-gtest
    - ros-foxy-ament-cmake-pytest
    - ros-foxy-ament-cmake-python
    - ros-foxy-builtin-interfaces
    - ros-foxy-geometry-msgs
    - ros-foxy-message-filters
    - ros-foxy-python-cmake-module
    - ros-foxy-rcl-interfaces
    - ros-foxy-rclcpp
    - ros-foxy-rclcpp-action
    - ros-foxy-rclcpp-components
    - ros-foxy-rclpy
    - ros-foxy-std-msgs
    - ros-foxy-tf2
    - ros-foxy-tf2-msgs
    - ros-foxy-tf2-py
  run:
    - python
    - ros-foxy-builtin-interfaces
    - ros-foxy-geometry-msgs
    - ros-foxy-message-filters
    - ros-foxy-rcl-interfaces
    - ros-foxy-rclcpp
    - ros-foxy-rclcpp-action
    - ros-foxy-rclcpp-components
    - ros-foxy-rclpy
    - ros-foxy-std-msgs
    - ros-foxy-tf2
    - ros-foxy-tf2-msgs
    - ros-foxy-tf2-py
