package:
  name: ros-foxy-geometry2
  version: 0.13.9
source:
  git_url: https://github.com/ros2-gbp/geometry2-release.git
  git_rev: release/foxy/geometry2/0.13.9-1
  folder: ros-foxy-geometry2/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
  host:
    - python
    - ros-foxy-ament-cmake
  run:
    - python
    - ros-foxy-tf2
    - ros-foxy-tf2-bullet
    - ros-foxy-tf2-eigen
    - ros-foxy-tf2-geometry-msgs
    - ros-foxy-tf2-kdl
    - ros-foxy-tf2-msgs
    - ros-foxy-tf2-py
    - ros-foxy-tf2-ros
    - ros-foxy-tf2-sensor-msgs
    - ros-foxy-tf2-tools
