package:
  name: ros-foxy-rosidl-typesupport-fastrtps-cpp
  version: 1.0.2
source:
  git_url: https://github.com/ros2-gbp/rosidl_typesupport_fastrtps-release.git
  git_rev: release/foxy/rosidl_typesupport_fastrtps_cpp/1.0.2-1
  folder: ros-foxy-rosidl-typesupport-fastrtps-cpp/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
  host:
    - python
    - ros-foxy-ament-cmake
    - ros-foxy-ament-cmake-gtest
    - ros-foxy-ament-cmake-ros
    - ros-foxy-ament-lint-auto
    - ros-foxy-ament-lint-common
    - ros-foxy-fastcdr
    - ros-foxy-fastrtps
    - ros-foxy-fastrtps-cmake-module
    - ros-foxy-osrf-testing-tools-cpp
    - ros-foxy-performance-test-fixture
    - ros-foxy-rmw
    - ros-foxy-rosidl-cmake
    - ros-foxy-rosidl-runtime-c
    - ros-foxy-rosidl-runtime-cpp
  run:
    - python
    - ros-foxy-ament-cmake-ros
    - ros-foxy-fastcdr
    - ros-foxy-fastrtps
    - ros-foxy-fastrtps-cmake-module
    - ros-foxy-rmw
    - ros-foxy-rosidl-cmake
    - ros-foxy-rosidl-parser
    - ros-foxy-rosidl-runtime-c
    - ros-foxy-rosidl-runtime-cpp
    - ros-foxy-rosidl-typesupport-interface
