package:
  name: ros-foxy-rclpy
  version: 1.0.5
source:
  git_url: https://github.com/ros2-gbp/rclpy-release.git
  git_rev: release/foxy/rclpy/1.0.5-1
  folder: ros-foxy-rclpy/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
  host:
    - pytest
    - python
    - ros-foxy-ament-cmake
    - ros-foxy-ament-cmake-gtest
    - ros-foxy-ament-cmake-pytest
    - ros-foxy-ament-lint-auto
    - ros-foxy-ament-lint-common
    - ros-foxy-python-cmake-module
    - ros-foxy-rcl
    - ros-foxy-rcl-action
    - ros-foxy-rcl-yaml-param-parser
    - ros-foxy-rcutils
    - ros-foxy-rmw-implementation
    - ros-foxy-rmw-implementation-cmake
    - ros-foxy-rosidl-generator-py
    - ros-foxy-test-msgs
    - ros-foxy-unique-identifier-msgs
  run:
    - python
    - ros-foxy-ament-index-python
    - ros-foxy-builtin-interfaces
    - ros-foxy-rcl
    - ros-foxy-rcl-action
    - ros-foxy-rcl-interfaces
    - ros-foxy-rcl-yaml-param-parser
    - ros-foxy-rmw-implementation
    - ros-foxy-rosgraph-msgs
    - ros-foxy-rpyutils
    - ros-foxy-unique-identifier-msgs
