package:
  name: ros-foxy-rmw-fastrtps-shared-cpp
  version: 1.2.4
source:
  git_url: https://github.com/ros2-gbp/rmw_fastrtps-release.git
  git_rev: release/foxy/rmw_fastrtps_shared_cpp/1.2.4-1
  folder: ros-foxy-rmw-fastrtps-shared-cpp/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
  host:
    - python
    - ros-foxy-ament-cmake
    - ros-foxy-ament-cmake-ros
    - ros-foxy-ament-lint-auto
    - ros-foxy-ament-lint-common
    - ros-foxy-fastcdr
    - ros-foxy-fastrtps
    - ros-foxy-fastrtps-cmake-module
    - ros-foxy-osrf-testing-tools-cpp
    - ros-foxy-rcpputils
    - ros-foxy-rcutils
    - ros-foxy-rmw
    - ros-foxy-rmw-dds-common
  run:
    - python
    - ros-foxy-ament-cmake
    - ros-foxy-fastcdr
    - ros-foxy-fastrtps
    - ros-foxy-fastrtps-cmake-module
    - ros-foxy-rcpputils
    - ros-foxy-rcutils
    - ros-foxy-rmw
    - ros-foxy-rmw-dds-common
