package:
  name: ros-foxy-rosbag2-converter-default-plugins
  version: 0.3.7
source:
  git_url: https://github.com/ros2-gbp/rosbag2-release.git
  git_rev: release/foxy/rosbag2_converter_default_plugins/0.3.7-1
  folder: ros-foxy-rosbag2-converter-default-plugins/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
  host:
    - python
    - ros-foxy-ament-cmake
    - ros-foxy-ament-cmake-gmock
    - ros-foxy-ament-index-cpp
    - ros-foxy-ament-lint-auto
    - ros-foxy-ament-lint-common
    - ros-foxy-pluginlib
    - ros-foxy-rcpputils
    - ros-foxy-rmw
    - ros-foxy-rmw-fastrtps-cpp
    - ros-foxy-rosbag2-cpp
    - ros-foxy-rosbag2-test-common
    - ros-foxy-rosidl-runtime-cpp
    - ros-foxy-test-msgs
  run:
    - python
    - ros-foxy-ament-index-cpp
    - ros-foxy-pluginlib
    - ros-foxy-rcpputils
    - ros-foxy-rmw
    - ros-foxy-rmw-fastrtps-cpp
    - ros-foxy-rosbag2-cpp
    - ros-foxy-rosidl-runtime-cpp
