package:
  name: ros-foxy-rcl-logging-spdlog
  version: 1.0.1
source:
  git_url: https://github.com/ros2-gbp/rcl_logging-release.git
  git_rev: release/foxy/rcl_logging_spdlog/1.0.1-1
  folder: ros-foxy-rcl-logging-spdlog/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
  host:
    - python
    - ros-foxy-ament-cmake-ros
    - ros-foxy-ament-lint-auto
    - ros-foxy-ament-lint-common
    - ros-foxy-rcutils
    - ros-foxy-spdlog-vendor
    - spdlog
  run:
    - python
    - ros-foxy-rcutils
    - ros-foxy-spdlog-vendor
    - spdlog
