package:
  name: ros-foxy-libstatistics-collector
  version: 1.0.1
source:
  git_url: https://github.com/ros-tooling/libstatistics_collector-release.git
  git_rev: release/foxy/libstatistics_collector/1.0.1-1
  folder: ros-foxy-libstatistics-collector/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
  host:
    - python
    - ros-foxy-ament-cmake
    - ros-foxy-ament-cmake-gtest
    - ros-foxy-ament-cmake-ros
    - ros-foxy-ament-lint-auto
    - ros-foxy-ament-lint-common
    - ros-foxy-rcl
    - ros-foxy-rcpputils
    - ros-foxy-rosidl-default-generators
    - ros-foxy-statistics-msgs
    - ros-foxy-std-msgs
  run:
    - python
    - ros-foxy-rcl
    - ros-foxy-rcpputils
    - ros-foxy-rosidl-default-runtime
    - ros-foxy-statistics-msgs
    - ros-foxy-std-msgs
