package:
  name: ros-foxy-class-loader
  version: 2.0.1
source:
  git_url: https://github.com/ros2-gbp/class_loader-release.git
  git_rev: release/foxy/class_loader/2.0.1-1
  folder: ros-foxy-class-loader/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
  host:
    - console_bridge
    - python
    - ros-foxy-ament-cmake
    - ros-foxy-ament-cmake-gtest
    - ros-foxy-ament-lint-auto
    - ros-foxy-ament-lint-common
    - ros-foxy-console-bridge-vendor
    - ros-foxy-rcpputils
  run:
    - console_bridge
    - python
    - ros-foxy-console-bridge-vendor
    - ros-foxy-rcpputils
