package:
  name: ros-foxy-robot-state-publisher
  version: 2.4.2
source:
  git_url: https://github.com/ros2-gbp/robot_state_publisher-release.git
  git_rev: release/foxy/robot_state_publisher/2.4.2-1
  folder: ros-foxy-robot-state-publisher/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
  host:
    - python
    - ros-foxy-ament-cmake
    - ros-foxy-ament-cmake-gtest
    - ros-foxy-ament-lint-auto
    - ros-foxy-ament-lint-common
    - ros-foxy-builtin-interfaces
    - ros-foxy-geometry-msgs
    - ros-foxy-kdl-parser
    - ros-foxy-launch-ros
    - ros-foxy-launch-testing-ament-cmake
    - ros-foxy-orocos-kdl
    - ros-foxy-rclcpp
    - ros-foxy-rclcpp-components
    - ros-foxy-sensor-msgs
    - ros-foxy-std-msgs
    - ros-foxy-tf2-ros
    - ros-foxy-urdf
    - ros-foxy-urdfdom-headers
  run:
    - python
    - ros-foxy-builtin-interfaces
    - ros-foxy-geometry-msgs
    - ros-foxy-kdl-parser
    - ros-foxy-orocos-kdl
    - ros-foxy-rclcpp
    - ros-foxy-rclcpp-components
    - ros-foxy-sensor-msgs
    - ros-foxy-std-msgs
    - ros-foxy-tf2-ros
    - ros-foxy-urdf
    - ros-foxy-urdfdom-headers
