package:
  name: ros-foxy-tf2
  version: 0.13.9
source:
  git_url: https://github.com/ros2-gbp/geometry2-release.git
  git_rev: release/foxy/tf2/0.13.9-1
  folder: ros-foxy-tf2/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
  host:
    - console_bridge
    - python
    - ros-foxy-ament-cmake
    - ros-foxy-ament-cmake-gtest
    - ros-foxy-console-bridge-vendor
    - ros-foxy-geometry-msgs
    - ros-foxy-rcutils
  run:
    - console_bridge
    - python
    - ros-foxy-console-bridge-vendor
    - ros-foxy-geometry-msgs
    - ros-foxy-rcutils
