package:
  name: ros-foxy-rosidl-generator-dds-idl
  version: 0.7.1
source:
  git_url: https://github.com/ros2-gbp/rosidl_dds-release.git
  git_rev: release/foxy/rosidl_generator_dds_idl/0.7.1-1
  folder: ros-foxy-rosidl-generator-dds-idl/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
  host:
    - python
    - ros-foxy-ament-cmake
    - ros-foxy-ament-lint-auto
    - ros-foxy-ament-lint-common
    - ros-foxy-rosidl-cmake
  run:
    - python
    - ros-foxy-ament-cmake
    - ros-foxy-rosidl-cmake
