package:
  name: ros-foxy-rcl-action
  version: 1.1.10
source:
  git_url: https://github.com/ros2-gbp/rcl-release.git
  git_rev: release/foxy/rcl_action/1.1.10-1
  folder: ros-foxy-rcl-action/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
  host:
    - python
    - ros-foxy-action-msgs
    - ros-foxy-ament-cmake-gtest
    - ros-foxy-ament-cmake-ros
    - ros-foxy-ament-lint-auto
    - ros-foxy-ament-lint-common
    - ros-foxy-osrf-testing-tools-cpp
    - ros-foxy-rcl
    - ros-foxy-rcutils
    - ros-foxy-rmw
    - ros-foxy-rmw-implementation-cmake
    - ros-foxy-rosidl-runtime-c
    - ros-foxy-test-msgs
  run:
    - python
    - ros-foxy-action-msgs
    - ros-foxy-rcl
    - ros-foxy-rcutils
    - ros-foxy-rmw
    - ros-foxy-rosidl-runtime-c
