package:
  name: ros-foxy-ros2test
  version: 0.2.1
source:
  git_url: https://github.com/ros2-gbp/ros_testing-release.git
  git_rev: release/foxy/ros2test/0.2.1-1
  folder: ros-foxy-ros2test/src/work

build:
  script:
    sel(win): bld_ament_python.bat
    sel(unix): build_ament_python.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
  host:
    - pytest
    - python
    - ros-foxy-ament-copyright
    - ros-foxy-ament-flake8
    - ros-foxy-ament-pep257
    - ros-foxy-launch
    - ros-foxy-launch-ros
    - ros-foxy-launch-testing
    - ros-foxy-launch-testing-ros
    - ros-foxy-ros2cli
  run:
    - python
    - ros-foxy-domain-coordinator
    - ros-foxy-launch
    - ros-foxy-launch-ros
    - ros-foxy-launch-testing
    - ros-foxy-launch-testing-ros
    - ros-foxy-ros2cli
