package:
  name: ros-foxy-rosidl-cmake
  version: 1.2.0
source:
  git_url: https://github.com/ros2-gbp/rosidl-release.git
  git_rev: release/foxy/rosidl_cmake/1.2.0-1
  folder: ros-foxy-rosidl-cmake/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
  host:
    - empy
    - python
    - ros-foxy-ament-cmake
    - ros-foxy-ament-cmake-python
    - ros-foxy-ament-lint-auto
    - ros-foxy-ament-lint-common
  run:
    - empy
    - python
    - ros-foxy-ament-cmake
    - ros-foxy-rosidl-adapter
    - ros-foxy-rosidl-parser
