package:
  name: ros-foxy-message-filters
  version: 3.2.5
source:
  git_url: https://github.com/ros2-gbp/ros2_message_filters-release.git
  git_rev: release/foxy/message_filters/3.2.5-1
  folder: ros-foxy-message-filters/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
  host:
    - python
    - ros-foxy-ament-cmake-gtest
    - ros-foxy-ament-cmake-pytest
    - ros-foxy-ament-cmake-python
    - ros-foxy-ament-cmake-ros
    - ros-foxy-ament-lint-auto
    - ros-foxy-builtin-interfaces
    - ros-foxy-python-cmake-module
    - ros-foxy-rclcpp
    - ros-foxy-rclpy
    - ros-foxy-sensor-msgs
    - ros-foxy-std-msgs
  run:
    - python
