package:
  name: ros-foxy-rosbag2
  version: 0.3.7
source:
  git_url: https://github.com/ros2-gbp/rosbag2-release.git
  git_rev: release/foxy/rosbag2/0.3.7-1
  folder: ros-foxy-rosbag2/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
  host:
    - python
    - ros-foxy-ament-cmake
    - ros-foxy-rosbag2-test-common
    - ros-foxy-rosbag2-tests
  run:
    - python
    - ros-foxy-ros2bag
    - ros-foxy-rosbag2-compression
    - ros-foxy-rosbag2-converter-default-plugins
    - ros-foxy-rosbag2-cpp
    - ros-foxy-rosbag2-storage
    - ros-foxy-rosbag2-storage-default-plugins
    - ros-foxy-rosbag2-transport
    - ros-foxy-shared-queues-vendor
    - ros-foxy-sqlite3-vendor
