package:
  name: ros-foxy-kdl-parser
  version: 2.4.1
source:
  git_url: https://github.com/ros2-gbp/kdl_parser-release.git
  git_rev: release/foxy/kdl_parser/2.4.1-2
  folder: ros-foxy-kdl-parser/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
  host:
    - python
    - ros-foxy-ament-cmake-ros
    - ros-foxy-ament-lint-auto
    - ros-foxy-ament-lint-common
    - ros-foxy-orocos-kdl
    - ros-foxy-tinyxml-vendor
    - ros-foxy-urdf
    - ros-foxy-urdfdom-headers
    - tinyxml
  run:
    - python
    - ros-foxy-orocos-kdl
    - ros-foxy-tinyxml-vendor
    - ros-foxy-urdf
    - ros-foxy-urdfdom-headers
    - tinyxml
