package:
  name: ros-foxy-rclcpp-lifecycle
  version: 2.3.0
source:
  git_url: https://github.com/ros2-gbp/rclcpp-release.git
  git_rev: release/foxy/rclcpp_lifecycle/2.3.0-1
  folder: ros-foxy-rclcpp-lifecycle/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
  host:
    - python
    - ros-foxy-ament-cmake-gtest
    - ros-foxy-ament-cmake-ros
    - ros-foxy-ament-lint-auto
    - ros-foxy-ament-lint-common
    - ros-foxy-lifecycle-msgs
    - ros-foxy-mimick-vendor
    - ros-foxy-performance-test-fixture
    - ros-foxy-rcl-lifecycle
    - ros-foxy-rclcpp
    - ros-foxy-rcutils
    - ros-foxy-rmw
    - ros-foxy-rosidl-typesupport-cpp
    - ros-foxy-test-msgs
  run:
    - python
    - ros-foxy-lifecycle-msgs
    - ros-foxy-rcl-lifecycle
    - ros-foxy-rclcpp
    - ros-foxy-rmw
    - ros-foxy-rosidl-typesupport-cpp
