package:
  name: ros-foxy-rosidl-typesupport-cpp
  version: 1.0.1
source:
  git_url: https://github.com/ros2-gbp/rosidl_typesupport-release.git
  git_rev: release/foxy/rosidl_typesupport_cpp/1.0.1-1
  folder: ros-foxy-rosidl-typesupport-cpp/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
  host:
    - python
    - ros-foxy-ament-cmake-core
    - ros-foxy-ament-cmake-ros
    - ros-foxy-ament-lint-auto
    - ros-foxy-ament-lint-common
    - ros-foxy-performance-test-fixture
    - ros-foxy-rcpputils
    - ros-foxy-rosidl-runtime-c
    - ros-foxy-rosidl-runtime-cpp
    - ros-foxy-rosidl-typesupport-c
    - ros-foxy-rosidl-typesupport-connext-cpp
    - ros-foxy-rosidl-typesupport-fastrtps-cpp
    - ros-foxy-rosidl-typesupport-introspection-cpp
  run:
    - python
    - ros-foxy-ament-cmake-core
    - ros-foxy-rcpputils
    - ros-foxy-rosidl-runtime-c
    - ros-foxy-rosidl-runtime-cpp
    - ros-foxy-rosidl-typesupport-c
    - ros-foxy-rosidl-typesupport-connext-cpp
    - ros-foxy-rosidl-typesupport-fastrtps-cpp
    - ros-foxy-rosidl-typesupport-interface
    - ros-foxy-rosidl-typesupport-introspection-cpp
